"""Ed Seykota 文字档案。字段说明见 _template.py。
文中标记：[[s:来源ID]] = 出处角标；[[t:词条ID|显示文字]] = 可点开的词条。
资料核查日期 2026-10-03。主干是 Market Wizards（1989）的采访原文（本站逐字读过 Seykota、Marcus、Hite 三章），
其次是他本人网站 seykota.com 和他与 Dave Druz 1993 年的论文。英文原话都能对上原文；只有 Covel 书里那句是经维基语录转引。"""

P = dict(
    slug='seykota',
    lang='en',
    title='Ed Seykota 资料汇编',
    description='美国期货交易员 Ed Seykota（艾德·塞柯塔）的中文资料汇编：生平时间线、模型账户业绩口径、趋势跟踪与风险热度方法、糖市场案例与公开教学系统的仓位算法、英文原话、常见说法辨析与 {sources} 条出处。',
    kicker='USA · 1970 年代— · 系统交易先驱',
    h1='Ed Seykota', h1_sub='艾德·塞柯塔 资料汇编',
    lede='1970 年代初，刚从 MIT 毕业的塞柯塔借券商会计部门的 IBM 360，在周末用打孔卡回测趋势跟踪规则，做出了第一套大规模商业化的期货计算机交易系统。'
         '他的“模型账户”1972 年以 <b>5,000 美元</b>起步，到 1988 年中现金回报超过 <b>250,000%</b>；Jack Schwager 在 Market Wizards 里说，没见过哪位交易员在同样长的时间里做到这种成绩。'
         '他是 Michael Marcus 的领路人，后来把越来越多的精力放到交易心理上，创办了 Trading Tribe。本页根据采访原文、他本人的网站和论文整理，<b>每条都标了出处</b>。',
    facts=[('全名', 'Edward Arthur Seykota'), ('出生', '1946 年 8 月 7 日'), ('学历', 'MIT 电气工程、斯隆管理学院双学士（1969）'),
           ('市场', '美国商品与金融期货'), ('风格', '计算机趋势跟踪 + 资金管理'), ('身份', '替少数客户管账户，只收盈利提成'),
           ('另一面', 'Trading Tribe 创办人、作者、乐手'), ('居住', '曾住太浩湖畔（内华达州），后迁往得州')],
    facts_src='[[s:wp]][[s:mw]]',
    strip=[('$5,000', '模型账户起步（1972）'), ('250,000%+', '截至 1988 年中的现金回报'), ('< 5%', '单笔风险上限（自述）'),
           ('约 100 种', '周末在 IBM 360 上回测的系统变体'), ('1992', '开始组织 Trading Tribe')],
    warn='<b>业绩数字只有一个账户</b>：他不公开整体业绩，只公开这个“模型账户”，没有经审计的记录可以核对，1988 年以后的成绩也没有公开。'
         '他的实盘系统是商业秘密；本页拆解的 EMA 交叉系统是他 2005 年在网站上带读者做的教学项目。仅供学习参考，不构成投资建议。',
    sections=[
        dict(id='brief', kind='brief', no='01', en='AT A GLANCE', title='一页看懂', items=[
            '<b>工程师出身的系统交易先驱</b>：1960 年代末读到 Richard Donchian 的通信，说纯机械的[[t:trend|趋势跟踪]]系统能跑赢市场。他用打孔卡写程序检验，结果成立。[[s:mw]]',
            '<b>只看趋势，不猜顶底</b>：重要性依次是长期趋势、当前图形、好的进出点；基本面“远远排在第四”，而且总的来看大概让他亏了钱。[[s:mw]]',
            '<b>止损，止损，还是止损</b>：建仓时同时下保护性止损，单笔风险控制在 5% 以内；连续亏损时缩小交易规模，等它过去。[[s:mw]]',
            '<b>仓位比时机重要</b>：他和 Dave Druz 1993 年的论文认为，设定组合的[[t:heat|风险热度]]远比调整进出场参数重要。[[s:or93]]',
            '<b>系统得合脾气</b>：“系统不需要改，诀窍是建立一套你能与之相容的系统。”他承认自己有时会推翻信号，也说系统交易归根到底是主观的。[[s:mw]]',
            '<b>交易就是心理</b>：“输也好赢也好，每个人都从市场得到了自己想要的。”1992 年起他组织交易员小组处理情绪，后来发展成 Trading Tribe。[[s:mw]][[s:wp]]',
        ]),
        dict(id='record', kind='table', no='02', en='TRACK RECORD', title='业绩口径：一个账户，几个数字',
             intro='他说自己<b>不公开整体业绩</b>，只公开一个“模型账户”，而且很少接新客户，接之前要面谈筛选客户的动机和心态。下面把书里出现过的数字逐条列出，并注明各自的口径。',
             cols=['数字', '指什么', '出处'], hl=[0],
             rows=[
                 ('$5,000 → 250,000%+', '一个真实客户账户（他称为[[t:model|模型账户]]）1972 年起步，到 1988 年中按[[t:cash|现金对现金]]计算的回报。', '[[s:mw]]'),
                 ('超过 1,500 万美元', '同一账户的累计盈利，是他本人的说法。他说如果没有提款，总回报会大很多倍；Schwager 写的是“理论上达数百万个百分点”。', '[[s:mw]]'),
                 ('约 60%—65% / 年', '本站按 250,000%、约 16 年倒推的年复合回报。未计提款，实际更高；只代表这一个账户。', '[[s:mw]]'),
                 ('1,500 万 / 1,000 万美元', '1970 年代初他管约六个账户，到采访时还留着四个。一位客户赚了约 1,500 万后撤资自己管理；另一位赚了 1,000 多万，买了海边的房子退休。', '[[s:mw]]'),
                 ('60%（理论）', '他早年在券商做的系统某一年的理论回报。管理层不断干预信号，不少账户当年实际亏钱，见下文“糖”的案例。', '[[s:mw]]'),
                 ('1987 年 10 月', '股灾当天、当月和全年都赚钱；第二天因为做空利率期货亏了一笔。', '[[s:mw]]'),
                 ('1980 年', '他自己说的最差年份之一：牛市结束了，他还想在低位买回；那是他第一次经历大熊市。', '[[s:mw]]'),
             ],
             notes=['“5,000 美元变 1,500 万”常被说成“12 年”。按书中时间是 1972 年到 1988 年中，约 16 年，见下文“说法辨析”。[[s:tt]]',
                    '书里没有给出他管理的总资金规模，也没有逐年回报。']),
        dict(id='life', kind='timeline', no='03', en='TIMELINE', title='生平时间线', items=[
            ('1946-08-07', '出生', '', ['wp']),
            ('1960 年代末', '第一笔交易：亏在“必涨”的白银上', '他认定美国财政部停售白银后银价必涨，开了保证金账户。等待期间听经纪人的话做空铜，被止损；等到“那一天”买入白银，价格反而下跌，又被止损。他说这是一堂“关于市场如何消化新闻的震撼教育”。', ['mw']),
            ('1969', 'MIT 双学士', 'MIT 电气工程学士，以及 MIT 斯隆管理学院的管理学学士。', ['wp']),
            ('约 1970', '用打孔卡检验 Donchian 的趋势系统', '他读到 Richard Donchian 的一封通信，说纯机械的趋势跟踪系统能跑赢市场，觉得不可能，于是写程序检验，结果成立。“到今天我也不确定自己明白为什么，也不确定是否需要明白。”', ['mw', 'wp']),
            ('1970 年代初', '第一份工作：券商分析师', '他负责鸡蛋和肉鸡期货。写文章建议读者暂时离场，被管理层从市场通讯里删掉；想用电脑做分析，又被电脑部门的主管赶走。约一个月后辞职。', ['mw']),
            ('1970 年代初', '第二家券商：周末借用 IBM 360', '公司刚改组，管理层大多被裁。他白天给路透电报机换纸、把新闻送给经纪人，周末用会计部门的 IBM 360 回测：约半年时间，测了 4 个简单系统的约 100 种变体，覆盖 10 个商品、约 10 年数据。', ['mw']),
            ('1971-10', '结识 Michael Marcus', 'Marcus 在经纪商办公室遇见他，后来称他为“天才”，说从他身上学会了止损、让利润奔跑，以及耐心跟随趋势。', ['mw_marcus']),
            ('1970 年代初', '第一套大规模商业化计算机交易系统', '管理层开始用他的研究成果管钱。系统由公司几百名经纪人销售，管理资金数百万美元，在当时是很大的数目。系统表现不错，但管理层不断推翻信号，见下文“糖”的案例。', ['mw']),
            ('1972', '“模型账户”开户', '一个客户账户以 5,000 美元起步，这是他后来唯一公开业绩的账户。', ['mw']),
            ('之后两年', '改为只收盈利提成', '他辞去研究部的职位，留下当经纪人管账户；约两年后放弃经纪业务，成为只按盈利收费的资金管理人。', ['mw']),
            ('1980', '最差年份之一', '牛市结束后，他还在“严重超买、超卖”的地方抄顶抄底。“市场一直走，我亏了很多。”后来他停手了一段时间。', ['mw']),
            ('1987-10', '股灾中赚钱', '崩盘当天、当月和全年都盈利；第二天因为做空利率市场亏损。', ['mw']),
            ('1988', '接受 Market Wizards 采访', 'Jack Schwager 到他在太浩湖畔的家中采访。他的桌上没有报价屏，每天收盘后花几分钟跑程序，生成第二天的信号。模型账户此时回报超过 250,000%。书于 1989 年出版。', ['mw']),
            ('1992', 'Trading Tribe 起步', '他召集一群交易员讨论情绪，此后定期聚会，逐渐发展成各地的 Trading Tribe 小组，以及一套称为 TTP 的做法。', ['wp', 'ttp']),
            ('1993-03', '与 Dave Druz 发表《Determining Optimal Risk》', '刊于《Technical Analysis of Stocks & Commodities》。作者简介写他当时经营 Technical Tools，一家提供历史和每日金融数据的公司。', ['or93']),
            ('2003 起', '在网站上答读者问', 'seykota.com 的 FAQ 从 2003 年起按旬或按月存档，一直延续到 2020 年代。', ['faqidx']),
            ('2005', '出版《The Trading Tribe》，公开教学系统', '书为 176 页精装本。同年他在网站上公开 EMA 交叉教学系统，读者到 9 月 11 日已把结果复现到分。', ['ttbook', 'tsp']),
            ('2008', '写下《The Whipsaw Song》', '借蓝草老歌《The Crawdad Song》的曲调，每段由一种乐器唱一条规则：让利润奔跑、砍掉亏损、管好风险、用止损单、坚持系统、把新闻扔进垃圾桶。', ['whipsaw']),
            ('2013', '出版《Govopoly in the 39th Day》', '讨论“Govopoly”（政府许可的垄断）体系自 1913 年起吞并自由竞争部门的长期趋势。同年发表 TTP 的修订版（Rocks Process）。', ['wp', 'govopoly']),
            ('2014-08', '提出“径向动量”升力理论', '他在网站上提出一套与教科书伯努利解释不同的升力理论，并做了一系列演示实验。这套理论没有被主流物理学接受，英文维基百科把他列入“伪科学物理学者”分类。', ['levitator', 'wp']),
        ]),
        dict(id='method', kind='methods', no='04', en='METHOD', title='交易方法：趋势、止损、仓位、心态',
             intro='他的实盘系统从未公开。下面每一条都来自他本人的采访、论文或网站；他自己说，这套方法的关键与其说在进出场信号，不如说在资金管理，以及交易者能不能长期执行。',
             items=[
                dict(t='趋势跟踪：买入止损单触发的那一刻转多', k='核心',
                     body='他说自己的风格“基本上是趋势跟踪，加上一些特殊的形态识别和资金管理算法”。重要性依次是：一、长期趋势；二、当前图形；三、选一个好的买卖点。买点设在市场<b>上方</b>，找动能会朝交易方向走强的位置，以降低风险，“我不去抓底或摸顶”。',
                     quote=('If I am bullish, I neither buy on a reaction, nor wait for strength; I am already in. I turn bullish at the instant my buy stop is hit, and stay bullish until my sell stop is hit.',
                            '如果我看多，我既不等回调去买，也不等走强再买：我已经在场内了。买入止损单被触发的那一刻我就转为看多，直到卖出止损单被触发。', 'mw', '1988 年采访'),
                     src=['mw']),
                dict(t='系统要和人相容', k='系统',
                     body='他的第一套系统是 Donchian 均线交叉系统的指数均线版，规则死板，不允许任何偏离。“我常常在最糟的时候跳上跳下，以为自己比系统聪明。”后来他更信任趋势、更能无视新闻，又不断加进“老手的规则”，系统才和他的风格合拍。他也说[[t:discretionary|系统交易归根到底是主观的]]：承担多少风险、做哪些市场、随资金涨落怎样加减规模，这些决定往往比进出场时机更重要。',
                     quote=("Systems don't need to be changed. The trick is for a trader to develop a system with which he is compatible.",
                            '系统不需要改。诀窍在于，交易者要建立一套自己能与之相容的系统。', 'mw', '1988 年采访'),
                     src=['mw']),
                dict(t='止损在先，单笔风险 5% 以内', k='风控',
                     body='建仓的同时下保护性[[t:stop|止损单]]，趋势延续时把止损往前移、锁住利润。市场太狂野时他有时提前了结，结果通常不比等止损更好，但能降低组合波动、“安抚神经”。他打算把单笔风险控制在 5% 以下，偶尔重大消息让清淡的市场跳空穿过止损，亏损才会超出。连续亏损时他缩小交易规模：“在连亏中硬做会让情绪崩溃，想把亏损‘追回来’则是致命的。”',
                     note='Larry Hite 在同一本书里转述他的风险观：冒 1%、5% 还是 10% 的险都可以，但冒得越多，结果波动越大。[[s:mw_hite]]',
                     src=['mw']),
                dict(t='仓位按风险热度和波动来定', k='仓位',
                     body='他和 Dave Druz 把所有持仓按止损计算的总风险叫作组合的[[t:heat|热度]]：五个市场各冒 2% 的险，和两个市场各冒 5%，热度都是 10%。论文的结论有三条：每个交易系统都有内在的最优热度；设定热度远比调整进出场参数重要；多数交易者对这两点都没有意识。2005 年的教学系统把它写成了公式：仓位 = 资金 × 热度 ÷（[[t:atr|ATR]] × 倍数）。',
                     src=['or93', 'tsp']),
                dict(t='不看新闻，不盯盘', k='信息',
                     body='大家都读到的基本面，他叫作“[[t:funny|funny-mentals]]”，因为市场早已把它反映在价格里；只有在别人相信之前就抓住的意外信息，才算有价值的“surprise-a-mentals”。他的桌上没有报价机，每天收盘后才取数据。市场通讯和别人口中“稳赢”的建议，他大多不理。',
                     quote=('Having a quote machine is like having a slot machine on your desk—you end up feeding it all day long.',
                            '桌上放一台报价机，就像放了一台老虎机：你最后会一整天往里喂钱。', 'mw', '1988 年采访'),
                     src=['mw']),
                dict(t='交易结果反映你真正想要的', k='心理',
                     body='他说心理是司机，分析是地图。他讲过一个交易者：每逢大牛市都把 1 万美元做到约 25 万，然后“性格一变”全部亏回，周而复始；塞柯塔认为对方从中得到了刺激、同情和关注。他用催眠、呼吸、视觉化、格式塔等方法帮交易者梳理目标，结果通常是“要么成功得多，要么发现自己其实不想当交易员”。这些做法后来发展成 Trading Tribe 的 [[t:ttp|TTP]]，用来找出并化解挡在人和“照系统做”之间的情绪。',
                     src=['mw', 'faq0310']),
             ],
             test='<b>能不能复制？</b>他在 Market Wizards 里给普通交易者的建议是：“找一位更出色的交易者替你交易，然后去找你真正热爱的事。”他也说趋势系统的盈利有周期：系统流行、用的人变多、行情转为无方向时，它们就会亏钱，资金不足和经验不足的人被洗出局，“长寿是成功的关键”。2005 年的教学系统公开了完整规则和数据，可以逐笔复现，适合拿来练手。[[s:mw]][[s:tsp]]'),
        dict(id='sugar', kind='case', no='05', en='CASE STUDY', title='糖：一年里最赚钱的一笔交易怎么变成亏损',
             intro='1970 年代初，他在券商做的计算机系统已经在替客户管钱。管理层熟悉 Donchian 的趋势系统，也喜欢“计算机系统”这个时髦词，却忍不住要对信号做二次判断。下面是他在采访里讲的经过。',
             steps=[('信号', '系统在糖价约 <b>5 美分</b>时发出买入信号。管理层认为已经超买，没有执行。'),
                    ('规则一', '改成“等第一次回调 20 点再买”（100 点等于 1 美分）。回调没有出现。'),
                    ('规则二', '再改成等 30 点回调，接着是 50 点，最后是 100 点。糖价一路上涨，始终没有像样的回调。'),
                    ('约 9 美分', '管理层终于认定这是牛市，赶在“涨得更高之前”给受管账户做多。'),
                    ('见顶', '不久糖价见顶。系统随后发出卖出信号，那个信号同样能赚很多钱，又被忽略。'),
                    ('年底', '全年最赚钱的一笔交易最后变成亏损。系统当年的理论回报是 60%，不少账户实际亏了钱。')],
             calc='5 美分 → 9 美分 = 4 美分 = 400 点<br>× 每美分 1,120 美元 / 张<br><span class="big">≈ 4,480 美元 / 张</span>',
             calc_note='这是从信号到实际入场之间，每张合约错过的涨幅。“每美分 1,120 美元”是 Schwager 在同一章里给糖合约的换算；当年的合约规格本站没有另行核对，只作量级参考。',
             calc_src=['mw'],
             his='“这类干预是我最后辞职的主要原因之一。”另一个原因是管理层要他把系统改得交易更频繁，好多收佣金。他说改起来很容易，但会严重损害业绩，“他们似乎不在乎”。[[s:mw]]',
             after=['他辞掉研究部的职位，留下当经纪人管账户；约两年后放弃经纪业务，只按盈利收费，因为靠佣金谋生“可能会与替客户赚钱的目标背道而驰”。[[s:mw]]',
                    '后来他在大糖牛市（10 美分涨到 40 美分）里持有数千张合约，离场时也付出了几美分的冲击成本：“当我想赶快从坏仓位里出来时，所有市场都太薄。”[[s:mw]]']),
        dict(id='tsp', kind='case', no='06', en='WORKED EXAMPLE', title='公开的教学系统：EMA 交叉 + ATR 仓位',
             intro='2005 年，他在网站上发起“交易系统项目”（TSP），公开了一套最简单的[[t:ema|指数均线]]交叉系统和数据，请读者用自己的软件复现，“精确到分”。到 9 月 11 日，已有读者复现成功。下面按网站给出的日志，走一遍第一笔交易。',
             steps=[('规则', '只做 S&P 500 [[t:continuous|连续合约]]，只做多。快线上穿慢线，次日开盘买入；下穿，次日开盘卖出。慢线滞后 150 天，快线 15 天。'),
                    ('成交', '按 50% [[t:skid|滑点]]成交：买价取开盘价与当日最高价的中点，卖价取开盘价与最低价的中点。不计佣金。'),
                    ('1982-08-31', '快线 113.590 上穿慢线 113.254，发出买入信号。当天 ATR 为 3.115。'),
                    ('1982-09-01', '开盘 119.30，最高 119.75，按中点 <b>119.525</b> 买入 6,500 单位。'),
                    ('1983-12-20', '以 159.60 卖出，这笔获利 <b>260,487.50 美元</b>。'),
                    ('整段回测', '150/15 这组参数最后约为初始资金的 3.3 倍，325/85 约为 13.6 倍。网站提示：慢系统加高热度、低 ATR 倍数赚得最多，[[t:drawdown|回撤]]也最大。')],
             calc='风险预算 = 100 万 × 10%（热度）= 10 万<br>每单位风险 = 5 × ATR 3.115 = 15.575<br>10 万 ÷ 15.575 = 6,420.5 → 取 250 的倍数<br><span class="big">6,500 单位</span>',
             calc_note='波动小就多买，波动大就少买：仓位只由资金、热度和 ATR 决定，与对行情的看法无关。1 单位等于每点 1 美元，250 单位相当于一张 S&P 500 合约。',
             calc_src=['tsp'],
             his='他在页面上说，优化参数有两种笨办法：凭手感一个个调（hunt-and-peck），或者把所有组合跑一遍（steamroller，十个参数各取 20 个值，就要跑 20 的 10 次方次）。最好是两者结合，再加上思考。热度很高的系统，回测还得考虑追加保证金，以及人的“胃口上限”（stomach calls）。[[s:tsp]]',
             after=['网站说明，这个项目是让 FAQ 读者参与系统的设计、验证、测试和实施，<b>没有说这就是他的实盘系统</b>。[[s:tsp]]',
                    '他早年的第一套系统也用指数均线：选它是因为“好算，而且计算误差会随时间消失”，当时被人口口相传为“expedential system”。[[s:mw]]']),
        dict(id='heat', kind='table', no='07', en='RISK', title='风险热度：抛硬币实验',
             intro='1993 年 3 月，他和 Dave Druz 在《Technical Analysis of Stocks & Commodities》上用一个游戏解释仓位：正面赢 2 倍赌注，反面输掉赌注，“这是好交易的一个公平模型”。每次押当前资金的固定比例，押多少最好？长期看正反面次数相等，顺序也不影响结果，所以只算一正一反一轮就够了。',
             caption='一轮“先正后反”的结果（起始资金 100）', cols=['每次押注', '正面后', '反面后（一轮结果）', '一轮收益'], num=[1, 2, 3], hl=[4],
             rows=[('5%', '110', '104.5', '+4.5%'), ('10%', '120', '108.0', '+8.0%'), ('15%', '130', '110.5', '+10.5%'), ('20%', '140', '112.0', '+12.0%'),
                   ('25%', '150', '112.5', '+12.5%'), ('30%', '160', '112.0', '+12.0%'), ('35%', '170', '110.5', '+10.5%'), ('40%', '180', '108.0', '+8.0%'),
                   ('45%', '190', '104.5', '+4.5%'), ('50%', '200', '100.0', '0')],
             notes=['最优押注是 25%：一轮赚 12.5%，中间先涨 50%、再回撤 25%。押得少时，收益随押注线性上升；超过最优之后亏损占上风，押到 50% 就是白忙一场。[[s:or93]]',
                    '论文说实践中可以押得比最优少一点，比如 15%—20%，少赚一点，换来更小的回撤压力。[[s:or93]]',
                    '他们在一个五市场组合上做了 12 年模拟：最优热度约 140%（每个市场约 28%），年化约 55%，平均回撤约 40%，最大回撤超过 90%。“实际上很少有投资者受得了这样的最优值。”[[s:or93]]',
                    '论文建议交易者在开始合作前，先用热度测试和投资人就押注大小、收益和回撤达成一致，免得交易做得不错，却因为热度太低或太高让投资人失望。[[s:or93]]']),
        dict(id='quotes', kind='quotes', no='08', en='IN HIS WORDS', title='语录',
             intro='英文原话大多出自 Market Wizards 的采访原文，另有几条来自他的网站和歌词；只有一条经维基语录转引自 Covel 的书。中文是本站的翻译。',
             items=[
                dict(ja='The elements of good trading are: (1) cutting losses, (2) cutting losses, and (3) cutting losses. If you can follow these three rules, you may have a chance.',
                     zh='好交易的要素是：一、砍掉亏损；二、砍掉亏损；三、砍掉亏损。能做到这三条，你也许有机会。', s='mw'),
                dict(ja='Win or lose, everybody gets what they want out of the market. Some people seem to like to lose, so they win by losing money.',
                     zh='输也好，赢也好，每个人都从市场得到了自己想要的。有些人似乎喜欢输，于是他们靠亏钱“赢”了。', s='mw'),
                dict(ja='Losing a position is aggravating, whereas losing your nerve is devastating.', zh='丢掉一个仓位让人恼火，丢掉胆量却是毁灭性的。', s='mw'),
                dict(ja='Pride is a great banana peel, as are hope, fear, and greed.', zh='骄傲是一块很大的香蕉皮，希望、恐惧和贪婪也是。', s='mw'),
                dict(ja='Psychology is the driver and analysis is the road map.', zh='心理是司机，分析是地图。', s='mw'),
                dict(ja='The markets are the same now as they were five to ten years ago because they keep changing—just like they did then.',
                     zh='市场和五到十年前一样，因为它一直在变，就像那时候一样。', s='mw'),
                dict(ja='Be sensitive to the subtle differences between ‘intuition’ and ‘into wishing.’', zh='要留意“直觉”（intuition）和“一厢情愿”（into wishing）之间的细微差别。', s='mw'),
                dict(ja='A lot of people would rather understand the market than make money.', zh='很多人宁可弄懂市场，也不愿赚钱。', s='mw'),
                dict(ja="I don't judge success. I celebrate it.", zh='我不评判成功，我庆祝它。', s='mw'),
                dict(ja="Risk no more than you can afford to lose, and also risk enough so that a win is meaningful. If there is no such amount, don't play.",
                     zh='冒的险不要超过你输得起的，也要大到赢了有意义。如果找不到这样的数额，就别玩。', s='covel'),
                dict(ja='One use of TTP is to locate and dissolve the feelings that stand between you and following your system.',
                     zh='TTP 的一个用处，是找出并化解那些挡在你和“照系统做”之间的情绪。', s='faq0310'),
                dict(ja="You get a whip and I get a saw … One good trend pays for em all.", zh='你挨一鞭，我挨一锯，来回被打脸……一波好趋势就能全赚回来。（《The Whipsaw Song》副歌）', s='whipsaw'),
            ]),
        dict(id='myths', kind='myths', no='09', en='FACT CHECK', title='说法辨析',
             intro='中英文网络上关于他的说法不少，下面逐条对照能找到的原始出处。',
             items=[
                ('5,000 美元用 12 年变成 1,500 万', '有出入', 'Market Wizards 写的是 1972 年起步，截至 1988 年中，约 16 年。“12 年”的说法在英文网站上流传，例如 TurtleTrader 的介绍页。', ['mw', 'tt']),
                ('250,000% 是他的整体业绩', '不对', '这是一个客户账户（“模型账户”）的现金回报。他明确说其他业绩不公开，书里也没有他管理的总资金规模。', ['mw']),
                ('他是纯机械交易，从不干预系统', '不完全对', '他说自己越来越机械化，但有时会凭强烈的感觉推翻信号，有时干脆停手，这部分“大概打平或略亏”。他认为给自己留这点自由，可以避免压抑到某天“爆掉”。', ['mw']),
                ('他不设止损，死扛趋势', '有出入', 'Marcus 回忆，塞柯塔有一次做多咖啡没下止损，连续几天被锁在[[t:limit|跌停]]里。塞柯塔在自己的访谈里则说，建仓时就下保护性止损，并随趋势移动。两种说法出自不同的人、不同的时期。', ['mw_marcus', 'mw']),
                ('他是 Commodities Corporation 的交易员', '无从核实', 'Market Wizards 里，Commodities Corporation 出现在 Marcus 的经历中；塞柯塔那一章只说他先后在两家券商工作，后来自己管账户。英文维基的 Commodities Corporation 条目和 TurtleTrader 都把他列为与该公司有关的人物，但没有给出处。', ['mw_marcus', 'mw', 'wp_cc', 'tt']),
                ('The trend is your friend except at the end where it bends 这句是他说的', '无从核实', '这句话常被记在他名下，但 Market Wizards 的采访里没有。维基语录给的出处是 Schwager 1995 年的《Technical Analysis》，本站没有见到原书，无法确认书中怎样署名。', ['mw', 'wq']),
                ('TTP 是一种心理治疗', '不完全对', '他把 TTP 定位为促进个人成长的“教育技术”。网站声明不建议有既往病症的人参加，正在接受治疗的人应先问过自己的治疗师。', ['ttp']),
            ]),
        dict(id='glossary', kind='glossary', no='10', en='GLOSSARY', title='用语'),
        dict(id='sources', kind='sources', no='11', en='SOURCES', title='资料来源',
             intro='“原文”指本站直接读到的书页、论文或网页；“转引”指只读到别人摘录的版本；“二次”是第三方汇编。Market Wizards 三章依据的是 archive.org 上的全文扫描本。'),
    ],
    terms={
        'trend': ('趋势跟踪', 'Trend following', '不预测涨跌，价格形成趋势后跟进、趋势反转时离场的交易方式。单笔胜率往往不高，靠少数大趋势覆盖多次小亏。'),
        'ema': ('指数移动平均', 'Exponential moving average · EMA', '对近期价格赋予更高权重的均线。塞柯塔说他早年选它，是因为计算简单，而且误差会随时间衰减。'),
        'stop': ('止损单', 'Stop order · protective stop', '价格触及指定价位就转为市价单的委托。保护性止损用来限制亏损；买入止损单挂在现价上方，价格向上突破时自动入场。'),
        'heat': ('风险热度', 'Portfolio heat', '塞柯塔和 Druz 的用语：所有持仓按止损计算的总风险占资金的比例。五个市场各冒 2% 的险，热度就是 10%。'),
        'atr': ('平均真实波幅', 'Average True Range · ATR', '衡量每日波动幅度的指标：取当日最高价、最低价和前一日收盘价之间的最大差距，再求平均。常用来按波动决定止损距离和仓位。'),
        'skid': ('滑点', 'Skid', '实际成交价比理论价格差出的部分。塞柯塔的教学系统假设 50% 滑点。交易越频繁，滑点对结果的影响越大。'),
        'whipsaw': ('来回打脸', 'Whipsaw', '价格反复穿越信号线，趋势系统刚买就止损、刚卖又反弹，连续小亏。他的歌里唱：一波好趋势就能把这些都赚回来。'),
        'drawdown': ('回撤', 'Drawdown', '资金从前一个高点往下跌的幅度。押注越大，回撤越深。'),
        'continuous': ('连续合约', 'Continuous contract · Panama', '把不同到期月份的期货合约拼成一条长价格序列，便于回测。“Panama”拼接法在换月时平移历史价格，消除跳空。'),
        'funny': ('“好笑的基本面”', 'Funny-mentals / Surprise-a-mentals', '塞柯塔的文字游戏：大家都读到的基本面（fundamentals）已经反映在价格里，是 funny-mentals；在别人相信之前就抓住的意外信息才有价值，是 surprise-a-mentals。'),
        'model': ('模型账户', 'Model account', '塞柯塔唯一公开业绩的那个真实客户账户，1972 年以 5,000 美元起步。'),
        'cash': ('现金对现金回报', 'Cash-on-cash', '只按实际投入和取回的现金计算的回报，不考虑提款后少掉的复利。模型账户有提款，所以 Schwager 说“标准化”后的理论回报远高于此。'),
        'discretionary': ('主观交易', 'Discretionary trading', '由交易者临场判断下单，相对于按规则执行的系统交易。塞柯塔认为，系统交易中关于风险、市场和规模的决定本身就是主观的。'),
        'limit': ('涨跌停', 'Limit up / limit down', '美国商品期货交易所对单日价格波动设有上限，触及后价格被“锁住”，可能连续几天都无法成交离场。'),
        'ttp': ('交易部落流程', 'TTP · Trading Tribe Process', '塞柯塔在 Trading Tribe 小组里使用的一套做法：一个人讲出并体验自己的感受，其他人鼓励他把感受放大、体验到底，用来化解妨碍执行系统的情绪。'),
        'fred': ('Fred', 'Fred', '塞柯塔对潜意识的称呼，指本能和边缘系统，负责说话、骑车、碰到烫的东西缩手这类不经过意识的反应。TTP 的工作之一，是让意识“听见” Fred 送来的感受。'),
    },
    sources={
        # id: (标题, 媒体, 日期, 链接, 类型)  类型：原文 / 转引 / 二次
        'mw': ('Ed Seykota — Everybody Gets What They Want（采访章节）', 'Market Wizards · Jack D. Schwager · New York Institute of Finance', '1989', 'https://archive.org/details/marketwizardsint00schw', '原文'),
        'mw_marcus': ('Michael Marcus — Blight Never Strikes Twice（采访章节）', 'Market Wizards · Jack D. Schwager', '1989', None, '原文'),
        'mw_hite': ('Larry Hite — Respecting Risk（采访章节）', 'Market Wizards · Jack D. Schwager', '1989', None, '原文'),
        'or93': ('Determining Optimal Risk（与 Dave Druz 合著）', 'Technical Analysis of Stocks & Commodities · V.11:3', '1993-03', 'https://store.traders.com/-v11-c03-determi-pdf.html', '原文'),
        'tsp': ('A Simple Trading System: Exponential Average Crossover（TSP 交易系统项目）', 'seykota.com', '2005', 'https://www.seykota.com/tribe/TSP/EA/index.htm', '原文'),
        'ttp': ('TTP – The Trading Tribe Process', 'seykota.com', '2026-10-03 查阅', 'https://www.seykota.com/tribe/TT_Process/index.htm', '原文'),
        'faq0310': ('FAQ，2003 年 10 月 26—31 日', 'seykota.com', '2003-10', 'https://www.seykota.com/tribe/pages/2003_Oct/Oct_26-31/index.htm', '原文'),
        'faqidx': ('FAQ Index（2003 年起的问答存档）', 'seykota.com', '2026-10-03 查阅', 'https://www.seykota.com/tt/FAQ_Index/', '原文'),
        'ttbook': ('The Trading Tribe Book（书籍介绍与读者来信）', 'seykota.com', '2005', 'https://www.seykota.com/tribe/Book/index.htm', '原文'),
        'whipsaw': ('The Whipsaw Song：歌词、乐谱与 MP3', 'seykota.com', '2008', 'https://www.seykota.com/tribe/essentials/downloads.htm', '原文'),
        'govopoly': ('Govopoly in the 39th Day（书籍网站）', 'govopoly.com', '2026-10-03 查阅', 'https://www.govopoly.com', '原文'),
        'levitator': ('Radial Momentum: An Alternate Theory of Lift', 'seykota.com', '2014-08-19', 'https://www.seykota.com/tribe/Levitator/index.htm', '原文'),
        'covel': ('Trend Following（第 59 页引语，经维基语录转引）', 'Michael W. Covel · FT Press', '2007', None, '转引'),
        'wq': ('Ed Seykota', '英文维基语录（Wikiquote）', '2026-10-03 查阅', 'https://en.wikiquote.org/wiki/Ed_Seykota', '二次'),
        'wp': ('Ed Seykota', '英文维基百科', '2026-10-03 查阅', 'https://en.wikipedia.org/wiki/Ed_Seykota', '二次'),
        'wp_cc': ('Commodities Corporation', '英文维基百科', '2026-10-03 查阅', 'https://en.wikipedia.org/wiki/Commodities_Corporation', '二次'),
        'tt': ('Ed Seykota: Top Market Wizard and Trend Following Trader', 'TurtleTrader.com', '2026-10-03 查阅', 'https://www.turtletrader.com/trader-seykota', '二次'),
    },
)
